export const keepWatchingMediaCard = [
    {title:'Naruto', genero:'Anime', linkImg:'naruto_classic.jpg'},
    {title:'The chosen', genero:'gospel', linkImg:'the_chosen.jpg'},
    {title:'Os Pinguins de Madagascar', genero:'Animação', linkImg:'os_pinguins.jpg'},
    {title:'Anne With An E', genero:'Drama', linkImg:'anne_with_an_e.jpg'},
    {title:'Madagascar 2', genero:'Animação', linkImg:'madagascar2.jpg'},
    {title:'Angry Birds', genero:'Animação', linkImg:'angry_birds.png'},
    {title:'The Witcher', genero:'Ação', linkImg:'The_witcher.jpg'},
    {title:'Homem aranah no aranha verso', genero:'Animação', linkImg:'homem_aranha_aranha_verso.jpg'},
    {title:'The flash', genero:'Ação', linkImg:'flash.jpg'},
    {title:'One Piece Live Action', genero:'aventura', linkImg:'One_Piece_live_action.jpg'},
    {title:'One Piece', genero:'Anime', linkImg:'One_piece.jpg'},
    {title:'Naruto Shippuden', genero:'Anime', linkImg:'Naruto_shippuden.jpg'},
    {title:'Pets', genero:'Animação', linkImg:'pets.jpg'},
    {title:'Black Clover', genero:'Anime', linkImg:'black_clover.jpg'},
    {title:'Hunter X Hunter', genero:'Anime', linkImg:'hunter_x_hunter.jpg'},
    {title:'One Punch Man', genero:'Anime', linkImg:'One-Punch.jpg'},
    {title:'Demon Slayer', genero:'Anime', linkImg:'demon_slayer.jpg'},
    {title:'Kung Fu Panda 3', genero:'Animação', linkImg:'kung_fu_panda.jpg'},
    {title:'Minions 2', genero:'Animação', linkImg:'minions_2.jpg'},
    {title:'Resgate 2', genero:'Ação', linkImg:'resgate_2.jpg'},
];


export const AllMediaCard = [
    {title:'The chosen', genero:'Gospel', linkImg:'the_chosen.jpg'},
    {title:'Naruto', genero:'Anime', linkImg:'naruto_classic.jpg'},
    {title:'Os Pinguins de Madagascar', genero:'Animação', linkImg:'os_pinguins.jpg'},
    {title:'Anne With An E', genero:'Drama', linkImg:'anne_with_an_e.jpg'},
    {title:'Madagascar 2', genero:'Animação', linkImg:'madagascar2.jpg'},
    {title:'Angry Birds', genero:'Animação', linkImg:'angry_birds.png'},
    {title:'The Witcher', genero:'Ação', linkImg:'The_witcher.jpg'},
    {title:'Homem aranah no aranha verso', genero:'Animação', linkImg:'homem_aranha_aranha_verso.jpg'},
    {title:'The flash', genero:'Ação', linkImg:'flash.jpg'},
    {title:'One Piece Live Action', genero:'Ação', linkImg:'One_Piece_live_action.jpg'},
    {title:'One Piece', genero:'Anime', linkImg:'One_piece.jpg'},
    {title:'Naruto Shippuden', genero:'Anime', linkImg:'Naruto_shippuden.jpg'},
    {title:'Pets', genero:'Animação', linkImg:'pets.jpg'},
    {title:'Black Clover', genero:'Anime', linkImg:'black_clover.jpg'},
    {title:'Hunter X Hunter', genero:'Anime', linkImg:'hunter_x_hunter.jpg'},
    {title:'One Punch Man', genero:'Anime', linkImg:'One-Punch.jpg'},
    {title:'Demon Slayer', genero:'Anime', linkImg:'demon_slayer.jpg'},
    {title:'Kung Fu Panda 3', genero:'Animação', linkImg:'kung_fu_panda.jpg'},
    {title:'Minions 2', genero:'Animação', linkImg:'minions_2.jpg'},
    {title:'Resgate 2', genero:'Ação', linkImg:'resgate_2.jpg'},
    {title:'Esquadrão 6', genero:'Ação', linkImg:'esquadrao_6.jpg'},
    {title:'Hancock', genero:'Ação', linkImg:'hancock.jpg'},
    {title:'Venom', genero:'Ação', linkImg:'Venom.png'},
    {title:'Velozes e Furiosos 6', genero:'Ação', linkImg:'velozes_e_furiosos_6.jpg'},
    {title:'A cabana', genero:'Drama', linkImg:'a_cabana.jpg'},
    {title:'Meu primeiro amor', genero:'Drama', linkImg:'meu_primeiro_amor.jpg'},
    {title:'Extraordinario', genero:'Drama', linkImg:'extraordinario.jpg'},
    {title:'O menino do pijama listrado', genero:'Drama', linkImg:'O_menino_do_pijama_listrado.jpg'},
    {title:'A procura da felicidade', genero:'Drama', linkImg:'A_procura_da_felicidade.jpg'},
    {title:'Quarto de guerra', genero:'Gospel', linkImg:'quarto_de_guerra.jpeg'},
    {title:'Deus não esta morto 2', genero:'Gospel', linkImg:'Deus_nao_esta_morto_2.jpg'},
    {title:'Amor de redencao', genero:'Gospel', linkImg:'amor_de_redencao.jpg'},
    {title:'No ritmo da fe', genero:'Gospel', linkImg:'no_ritmo_da_fe.jpg'},
    {title:'Jogada de rei', genero:'Gospel', linkImg:'jogada_de_rei.jpg'},
    
];